feat: python nb toolkit
vegaprotocol/vega-market-sim pull request #142
Opened 2022-09-06 14:06 UTC by cdummett

### Description
Toolkit for creating Python parameter test notebooks added. StakeTargetScaling notebook converted to use toolkit as demo.

### Testing
None - REQUIRED

### Breaking Changes
None

### Closes
None

2022-09-13 13:06 UTC, TomMcL requested changes
LGTM, a couple of small tweaks (particularly let's try and get rid of that magic number)

2022-09-13 13:06 UTC, TomMcL commented on parameter_results/toolkit.py
> +            path (str): Path to directory containing parameter test files.
Missing docstring for dt

2022-09-13 13:06 UTC, TomMcL commented on parameter_results/toolkit.py
> +        variables: list = None,
Optional[List[str]]

2022-09-13 13:06 UTC, TomMcL commented on parameter_results/toolkit.py
> +            if time_step != 289:
289?

2022-09-14 08:57 UTC, cdummett commented on parameter_results/toolkit.py
> +            if time_step != 289:
Yep good catch. this is left over from the original notebooks. I will find a way around it now.

2022-09-16 12:10 UTC, TomMcL approved these changes
LGTM. Generally I'd say clear the output in a notebook but probably good to have the examples here

2022-09-16 12:17 UTC, cdummett commented
Thanks, yeah thats good advice, hadn't thought of that. Will do that for future notebooks 👍

2022-09-16 12:18 UTC, merged