feat: add max margin and LP return
vegaprotocol/vega-market-sim pull request #188
Opened 2022-10-03 19:20 UTC by Jiajia-Cui

2022-10-03 19:45 UTC, Galen-Cao commented on vega_sim/parameter_test/parameter/loggers.py
> +
Could we maybe put calculation of max_margin & max_lockedCapital together to simplify the code? And maybe let `old_logs = state_values[-1]` should have the same result.

2022-10-04 08:59 UTC, TomMcL commented
What are the changes in the DemoNotebook here?

2022-10-04 09:20 UTC, Jiajia-Cui commented
> 

added the new outputs in `experiment.plot_results`

2022-10-04 09:34 UTC, TomMcL requested changes
Needs a `black` run too :+1:

2022-10-04 09:34 UTC, TomMcL commented on vega_sim/parameter_test/parameter/loggers.py
> +
Agreed on both

2022-10-04 09:34 UTC, TomMcL commented on vega_sim/parameter_test/parameter/loggers.py
> +        max_lockedCapital = max(margin_lp + bond_lp, max_lockedCapital)
`max_locked_capital`

2022-10-04 09:34 UTC, TomMcL commented on vega_sim/parameter_test/parameter/loggers.py
> +    state_values: List = None,
Still not really sure I like this vs just calculating derived values at a later time, though in the interests of expediency we can probably stick with it for now

2022-10-04 14:01 UTC, TomMcL commented
Needs another `make black` please 😄 (You can enable in VSCode so that it runs on save, which makes things easier!) 

Also, the DemoNotebook.ipynb file isn't for actual investigation, should just be a useful template to copy into the specific folders for each investigation. This one still looks reasonable though so will leave it for now!

2022-10-04 14:41 UTC, TomMcL approved these changes

2022-10-04 14:41 UTC, merged