feat: trades from stream improvements
vegaprotocol/vega-market-sim pull request #310
Opened 2023-01-17 18:25 UTC by TomMcL

### Description

Adding a filter to trades_from_stream to avoid trades you don't want being included in the return. Also freezing data class such that it can be returned without copying

### Testing

Tests pass

### Breaking Changes

Should be none

### Closes

#304

2023-01-18 09:43 UTC, cdummett submitted a review, later dismissed
LGTM

2023-01-20 14:11 UTC, davidsiska-vega requested changes
Looks good - my only thought is - do we want to hold off till the issue with the RL nightly runs is resolved? 

Or maybe let’s make the restart 100 iterations optional and not do that on the RL nightly runs (at least for now).

2023-01-20 14:12 UTC, davidsiska-vega approved these changes, later dismissed

2023-01-20 15:35 UTC, cdummett requested changes
Having an issue when running a scenario I am hanging after settling the market - means all my local tests are hanging as well.

Seems fine in the develop branch.

2023-01-20 15:35 UTC, cdummett commented on vega_sim/service.py
> +
Duplicated?

2023-01-20 17:35 UTC, TomMcL commented
@cdummett thanks for catching, looks like the kill signal got lost in the merge! Should be working again now 👍

2023-01-20 18:05 UTC, cdummett approved these changes

2023-01-20 18:13 UTC, merged