feat: add ledger_entries_subscription
vegaprotocol/vega-market-sim pull request #316
Opened 2023-01-19 17:41 UTC by cdummett

### Description
Adds service methods for running a subscription listening for ledger movement events from which individual ledger entries are extracted.

Method added so `TRANSFER_TYPE_LIQUIDITY_DISTRIBUTION` events can be identified, required for calculating liquidity fees gained for a party.

### Testing
Passing all tests locally.

### Breaking Changes
None

2023-01-19 19:03 UTC, TomMcL requested changes

2023-01-19 19:03 UTC, TomMcL commented on vega_sim/service.py
> +        self.trade_thread = None
Looks like these have snuck in

2023-01-19 19:04 UTC, TomMcL commented
Slightly concerned about whether we're going to reach a point where Python can't handle all these feeds, but we shall see 😄

2023-01-20 09:17 UTC, cdummett commented
> Slightly concerned about whether we're going to reach a point where Python can't handle all these feeds, but we shall see 😄

I agree.. maybe we should go back to optionally turning specific threads on? At the moment only need this thread for tracking liquidity distributions.

2023-01-20 09:18 UTC, cdummett commented on vega_sim/service.py
> +        self.trade_thread = None
Thanks, have removed!

2023-01-20 09:55 UTC, TomMcL approved these changes

2023-01-20 09:58 UTC, merged