Feat/wallet v2 upgrade
vegaprotocol/vega-market-sim pull request #332
Opened 2023-02-10 17:59 UTC by TomMcL

### Description

### Testing

### Breaking Changes

### Closes

2023-02-14 14:58 UTC, cdummett requested changes
Looks great! All the tests are passing for me!

I'm running into an issue though using the full vega wallet on nullchain:
 (changing `use_full_vega_wallet` to `True` in `adhoc.py`)

```
(vega-sim-py3.10) Charlies-MacBook-Pro:vega-market-sim caed$ python -m vega_sim.scenario.adhoc -s shaped_market_maker --console
INFO:vega_sim.null_service:Vega Running. Console launched at http://localhost:61728
INFO:vega_sim.null_service:Running NullChain from vegahome of /var/folders/mq/qntzn9jd0rngp7d0cj8nz9xh0000gn/T/vega-sim-2oxo_r29
INFO:vega_sim.null_service:Launching GraphQL node at port 61722
INFO:vega_sim.null_service:Launching Console at port 61728
INFO:vega_sim.environment.environment:Running wallet at: http://localhost:61719
INFO:vega_sim.environment.environment:Running graphql at: http://localhost:61722
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/caed/vega-market-sim/vega_sim/scenario/adhoc.py", line 76, in <module>
    main()
  File "/Users/caed/vega-market-sim/vega_sim/scenario/adhoc.py", line 56, in main
    scenario.run_iteration(
  File "/Users/caed/vega-market-sim/vega_sim/scenario/scenario.py", line 79, in run_iteration
    outputs = self.env.run(
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 150, in run
    return self._run(self._vega, pause_at_completion=pause_at_completion)
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 192, in _run
    agent.initialise(vega=vega)
  File "/Users/caed/vega-market-sim/vega_sim/scenario/common/agents.py", line 949, in initialise
    super().initialise(vega=vega, create_key=create_key)
  File "/Users/caed/vega-market-sim/vega_sim/environment/agent.py", line 80, in initialise
    self.vega.create_key(
  File "/Users/caed/vega-market-sim/vega_sim/service.py", line 309, in create_key
    return self.wallet.create_key(wallet_name=wallet_name, name=name)
  File "/Users/caed/vega-market-sim/vega_sim/wallet/vega_wallet.py", line 143, in create_key
    self.pub_keys.setdefault(wallet, {})[name] = json.loads(cmd)["publicKey"]
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
(vega-sim-py3.10) Charlies-MacBook-Pro:vega-market-sim caed$ 
```

Also what are the files in `vega_sim/data/wallets` and how are they showing in the changed files but not in my local branch?

2023-02-14 14:58 UTC, cdummett commented on scripts/update_vega_version.sh
> +# pytest -s -v --log-cli-level INFO -m integration
Is this one intentional?

2023-02-14 14:58 UTC, cdummett commented on vega_sim/wallet/base.py
>          """Return the public key associated with a given wallet name.
```suggestion
        """Return the public key associated with a given key name.
```

2023-02-14 14:58 UTC, cdummett commented on vega_sim/scenario/ideal_market_maker_v2/agents.py
>                  proposal_wallet=self.wallet_name,
Think this arg needs to be removed.

```
(vega-sim-py3.10) Charlies-MacBook-Pro:vega-market-sim caed$ python -m vega_sim.scenario.adhoc -s historic_ideal_market_maker_v2 --console
INFO:vega_sim.null_service:Vega Running. Console launched at http://localhost:54756
INFO:vega_sim.null_service:Running NullChain from vegahome of /var/folders/mq/qntzn9jd0rngp7d0cj8nz9xh0000gn/T/vega-sim-4zu2fzfh
INFO:vega_sim.null_service:Launching GraphQL node at port 54750
INFO:vega_sim.null_service:Launching Console at port 54756
INFO:vega_sim.environment.environment:Running wallet at: http://localhost:54747
INFO:vega_sim.environment.environment:Running graphql at: http://localhost:54750
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/caed/vega-market-sim/vega_sim/scenario/adhoc.py", line 76, in <module>
    main()
  File "/Users/caed/vega-market-sim/vega_sim/scenario/adhoc.py", line 56, in main
    scenario.run_iteration(
  File "/Users/caed/vega-market-sim/vega_sim/scenario/scenario.py", line 79, in run_iteration
    outputs = self.env.run(
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 150, in run
    return self._run(self._vega, pause_at_completion=pause_at_completion)
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 192, in _run
    agent.initialise(vega=vega)
  File "/Users/caed/vega-market-sim/vega_sim/scenario/ideal_market_maker_v2/agents.py", line 178, in initialise
    self.vega.create_simple_market(
TypeError: VegaService.create_simple_market() got an unexpected keyword argument 'proposal_wallet'
```

2023-02-14 15:08 UTC, cdummett commented on vega_sim/environment/agent.py
> +    def initialise(self, vega: VegaService, create_key: bool = True):
This change could be repeated in the parent method in `Agent`

2023-02-14 15:25 UTC, cdummett requested changes
Feedback from running against network:

In `environment.py` agents are still being initialised with the `create_wallet` flag which is causing issues:

```
(vega-sim-py3.10) Charlies-MacBook-Pro:vega-market-sim caed$ python -m devops.run -s ETHUSD -n STAGNET1 --console
✓ Importing the network succeeded

Name:
stagnet1
File path:
/Users/caed/Library/Application Support/vega/wallet-service/networks/stagnet1.toml
INFO:vega_sim.network_service:Vega Running. Console launched at http://localhost:52388
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/caed/vega-market-sim/devops/run.py", line 92, in <module>
    main()
  File "/Users/caed/vega-market-sim/devops/run.py", line 82, in main
    scenario.run_iteration(
  File "/Users/caed/vega-market-sim/vega_sim/scenario/scenario.py", line 79, in run_iteration
    outputs = self.env.run(
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 415, in run
    return self._run(self._vega, pause_at_completion=pause_at_completion)
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 427, in _run
    agent.initialise(vega=vega, create_wallet=False, mint_wallet=False)
TypeError: ConfigurableMarketManager.initialise() got an unexpected keyword argument 'create_wallet'
```

2023-02-14 15:25 UTC, cdummett commented on vega_sim/environment/agent.py
> +    def initialise(self, vega: VegaService, create_key: bool = True):
This change could be repeated in the parent method in `Agent` for clarity?

2023-02-15 10:09 UTC, TomMcL commented on scripts/update_vega_version.sh
> +# pytest -s -v --log-cli-level INFO -m integration
It is not :)

2023-02-15 10:17 UTC, TomMcL commented on vega_sim/environment/agent.py
> +    def initialise(self, vega: VegaService, create_key: bool = True):
:+1:

2023-02-15 10:25 UTC, TomMcL commented
The files in `data/wallets` are deleted which is why they don't show up locally 😄. They're old default wallets from long ago which I don't think we want anymore

2023-02-15 13:56 UTC, cdummett requested changes
One last change for wallet to work with networks:

in the `_start_live_methods` in the `MarketEnvironment` class, the call to `vega.wallet.public_key` has the key and wallet arguments the wrong way round.

2023-02-15 13:56 UTC, cdummett commented on vega_sim/environment/agent.py
> +        self, vega: VegaService, create_key: bool = False, mint_wallet: bool = False
I missed this first time, think `mint_wallet` should now be `mint_key` as well.

2023-02-15 14:03 UTC, cdummett requested changes
One more.

2023-02-15 14:04 UTC, cdummett requested changes

2023-02-15 14:04 UTC, cdummett commented on vega_sim/wallet/vega_wallet.py
> +        return {key["name"]: key["publicKey"] for key in response.json()["value"]}
This line isn't working for me running on a network.
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/caed/vega-market-sim/devops/run.py", line 92, in <module>
    main()
  File "/Users/caed/vega-market-sim/devops/run.py", line 82, in main
    scenario.run_iteration(
  File "/Users/caed/vega-market-sim/vega_sim/scenario/scenario.py", line 79, in run_iteration
    outputs = self.env.run(
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 415, in run
    return self._run(self._vega, pause_at_completion=pause_at_completion)
  File "/Users/caed/vega-market-sim/vega_sim/environment/environment.py", line 427, in _run
    agent.initialise(vega=vega, create_key=False, mint_key=False)
  File "/Users/caed/vega-market-sim/vega_sim/scenario/common/agents.py", line 1130, in initialise
    self.vega.submit_liquidity(
  File "/Users/caed/vega-market-sim/vega_sim/service.py", line 1354, in submit_liquidity
    return trading.submit_liquidity(
  File "/Users/caed/vega-market-sim/vega_sim/api/trading.py", line 381, in submit_liquidity
    wallet.submit_transaction(
  File "/Users/caed/vega-market-sim/vega_sim/wallet/vega_wallet.py", line 251, in submit_transaction
    pub_key = self.public_key(wallet_name=wallet_name, name=key_name)
  File "/Users/caed/vega-market-sim/vega_sim/wallet/vega_wallet.py", line 297, in public_key
    self.get_keypairs(wallet_name=wallet_name)
  File "/Users/caed/vega-market-sim/vega_sim/wallet/vega_wallet.py", line 236, in get_keypairs
    return {key["name"]: key["publicKey"] for key in response.json()["value"]}
KeyError: 'value'
```

Should it be:

```
return {key["name"]: key["publicKey"] for key in response.json()["result"]["keys"]}
```

2023-02-15 17:08 UTC, cdummett approved these changes

2023-02-16 17:38 UTC, merged