Fix/allow single port in port config
vegaprotocol/vega-market-sim pull request #438
Opened 2023-06-21 22:23 UTC by mattrussell36

### Description

Adjusts port config setup so that you can set a single port and not need to provide the whole port config

### Testing
Added an integration test `tset_port_config.py`

### Breaking Changes
I don't think so, but you might be able to remove some ports if you use port_config and only need to set a few of them

### Closes
N/A

2023-06-22 08:58 UTC, TomMcL requested changes

2023-06-22 08:58 UTC, TomMcL commented on vega_sim/null_service.py
> +    def _assign_ports(self, port_config):
```suggestion
    def _assign_ports(self, port_config: Optional[Dict[Ports, int]]):
```

2023-06-22 16:00 UTC, mattrussell36 commented on vega_sim/null_service.py
> +    def _assign_ports(self, port_config):
Done

2023-06-27 09:32 UTC, TomMcL approved these changes

2023-06-27 09:33 UTC, merged