feat: new spam test in progress
vegaprotocol/vega-market-sim pull request #523
Opened 2023-10-10 15:18 UTC by Sohill-Patel

### Description

### Testing

### Breaking Changes

### Closes

2023-10-12 09:05 UTC, davidsiska-vega requested changes
Even if we accept that null chain is enough to test spam:
The actual system test, testing the AC should live in the system test repo. So in the system test repo you can import the market sim package, run the tests you want on top of market sim / null chain. 

This ensures that 
a) the test is run as mandatory on PRs / included in overnight runs (as you set it)
b) market sim codebase is kept for it's purpose - which is market simulations.

2023-10-13 09:18 UTC, Sohill-Patel commented
```{“vega":"9755-spam-stats-extension"}```

2023-10-13 14:57 UTC, Sohill-Patel commented
```{"vega":"develop"}```

2023-10-13 16:13 UTC, cdummett requested changes
Two small comments - the tests and mods to the service classes look good though.

Just need to address Davids comments as the tests themselves might need to be moved to system-tests.

2023-10-13 16:13 UTC, cdummett commented on .env
This needs to be changed to a specific commit (whatever the recent develop commit is good - as long as it passing).

When you do make sure the protos are up to date with `make proto` 😉

2023-10-13 16:13 UTC, cdummett commented on Jenkinsfile
> +        string( name: 'VEGA_VERSION', defaultValue: 'cb2153cc1d6bba5d8ac348ed4b2bf8720c428630',
Make sure this matches what is in `.env`

2023-10-25 08:56 UTC, Sohill-Patel commented
moved to https://github.com/vegaprotocol/system-tests-nbc/pull/4

2023-10-25 08:56 UTC, closed without merging